default_url: "https://mainnet.infura.io/v3/your-project-id"

# Method-specific routing
default_name: "Infura Mainnet"
routes:
  - method: "eth_chainId"
    url: "https://polygon-rpc.com"
    name: "Polygon RPC"

  - method: "eth_blockNumber"
    url: "https://rpc.ankr.com/eth"
    name: "Ankr Ethereum"